#use an official Python runtime as a parent image
FROM continuumio/anaconda

# Set the working directory to /app
WORKDIR /NewPyApp

# Copy the current directory contents into the container at /app
ADD . /NewPyApp

# Install any needed packages specified in requirements.txt
# RUN pip install --trusted-host pypi.python.org -r requirements.txt --proxy 194.138.0.10:9400

RUN conda env create -f env.yaml

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["python", "newpy1.py"]
